"""
Assessment ORM model.

Generated by the Assessment Engine after LLM evaluation.
Linked 1:1 with a QuestSubmission.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import AssessmentStatus
from app.database import Base


class Assessment(Base):
    __tablename__ = "assessments"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    submission_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("quest_submissions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # 1:1 — one assessment per submission
        index=True,
    )
    status: Mapped[AssessmentStatus] = mapped_column(
        default=AssessmentStatus.PROCESSING, nullable=False
    )
    knowledge_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    reasoning_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    application_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    creation_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    overall_score: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    feedback: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )
    improvement_suggestions: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )
    assessed_at: Mapped[datetime | None] = mapped_column(
        DateTime, nullable=True
    )
    error_message: Mapped[str | None] = mapped_column(
        String(512), nullable=True
    )

    # Relationships
    submission: Mapped["QuestSubmission"] = relationship(
        "QuestSubmission", back_populates="assessment"
    )
