"""Seed initial Quests — single test quest for frontend verification.
All future quests are generated by the Agent when creating learning paths.
"""

from sqlalchemy.orm import Session

from app.quests.models import Quest
from app.core.enums import QuestDifficulty, QuestType, DeliverableType


SEED_QUESTS = [
    # ── Single test quest for frontend display verification ────
    {
        "skill_name": "Prompt Engineering",
        "title": "用户反馈分类器",
        "title_en": "User Feedback Classifier",
        "description": (
            "一家SaaS公司每天收到数百条用户反馈。"
            "运营团队无法手动分类。"
            "设计一个提示词，让AI自动将反馈分类为："
            "Bug、功能请求、投诉、好评。"
        ),
        "description_en": (
            "A SaaS company receives hundreds of user feedback items daily. "
            "The operations team can't manually sort them. "
            "Design a prompt that lets AI automatically classify feedback into: "
            "Bug, Feature Request, Complaint, Praise."
        ),
        "difficulty": QuestDifficulty.LEVEL_1,
        "quest_type": QuestType.APPLICATION,
        "expected_deliverable": DeliverableType.PROMPT,
    },
]


def run(db: Session, skill_ids: dict[str, str]) -> None:
    """Insert quests. skill_ids maps skill name → UUID string."""
    for data in SEED_QUESTS:
        sid = skill_ids.get(data.pop("skill_name"))
        if sid is None:
            continue

        existing = db.query(Quest).filter(
            Quest.title == data["title"],
            Quest.skill_id == sid,
        ).first()
        if existing:
            continue

        quest = Quest(skill_id=sid, **data)
        db.add(quest)

    db.commit()
