"""
Seed comprehensive building templates — one template per skill (~55 buildings).

Each building maps 1:1 to a Skill and belongs to one of 12 civilization types.
Buildings have 10-level evolution with level_names matching the design doc's growth ladders.
Idempotent — checks for existing templates before inserting.
"""
from sqlalchemy.orm import Session

from app.world.models import BuildingTemplate
from app.skills.models import Skill

# Level names for each civilization type (10 levels each)
# From docs/world design.md section 5 (文明建筑体系)
CIV_LEVEL_NAMES: dict[str, dict[str, dict[str, str]]] = {
    "KNOWLEDGE": {
        "1": {"zh": "学习营地", "en": "Learning Camp"},
        "2": {"zh": "木质学堂", "en": "Wooden School"},
        "3": {"zh": "乡镇学院", "en": "Town Academy"},
        "4": {"zh": "中央学院", "en": "Central College"},
        "5": {"zh": "大学", "en": "University"},
        "6": {"zh": "国家图书馆", "en": "National Library"},
        "7": {"zh": "文明档案馆", "en": "Archive of Civilization"},
        "8": {"zh": "知识殿堂", "en": "Knowledge Hall"},
        "9": {"zh": "世界智库", "en": "World Think Tank"},
        "10": {"zh": "文明图书馆", "en": "Library of Civilization"},
    },
    "ENGINEERING": {
        "1": {"zh": "手工工坊", "en": "Hand Workshop"},
        "2": {"zh": "铁匠铺", "en": "Blacksmith"},
        "3": {"zh": "制造车间", "en": "Manufacturing Plant"},
        "4": {"zh": "机械工厂", "en": "Machinery Factory"},
        "5": {"zh": "自动化工厂", "en": "Automated Factory"},
        "6": {"zh": "智能工厂", "en": "Smart Factory"},
        "7": {"zh": "工业园区", "en": "Industrial Park"},
        "8": {"zh": "超级制造中心", "en": "Super Manufacturing Center"},
        "9": {"zh": "全自动工业城", "en": "Fully Automated Industry City"},
        "10": {"zh": "文明制造核心", "en": "Civilization Manufacturing Core"},
    },
    "AI": {
        "1": {"zh": "算法小屋", "en": "Algorithm Hut"},
        "2": {"zh": "推理室", "en": "Reasoning Room"},
        "3": {"zh": "AI实验室", "en": "AI Lab"},
        "4": {"zh": "Agent工坊", "en": "Agent Workshop"},
        "5": {"zh": "Agent基地", "en": "Agent Base"},
        "6": {"zh": "智能研究院", "en": "Intelligence Institute"},
        "7": {"zh": "推理中心", "en": "Reasoning Center"},
        "8": {"zh": "AI议会", "en": "AI Parliament"},
        "9": {"zh": "超级智能塔", "en": "Super Intelligence Tower"},
        "10": {"zh": "智能文明核心", "en": "Intelligent Civilization Core"},
    },
    "BUSINESS": {
        "1": {"zh": "集市", "en": "Marketplace"},
        "2": {"zh": "商铺", "en": "Shop"},
        "3": {"zh": "商会", "en": "Trade Guild"},
        "4": {"zh": "贸易中心", "en": "Trade Center"},
        "5": {"zh": "商业大厦", "en": "Commercial Tower"},
        "6": {"zh": "企业总部", "en": "Corporate HQ"},
        "7": {"zh": "资本中心", "en": "Capital Center"},
        "8": {"zh": "全球贸易港", "en": "Global Trade Port"},
        "9": {"zh": "商业联盟", "en": "Business Alliance"},
        "10": {"zh": "经济中枢", "en": "Economic Hub"},
    },
    "DESIGN": {
        "1": {"zh": "画室", "en": "Studio"},
        "2": {"zh": "工作室", "en": "Workshop"},
        "3": {"zh": "创意中心", "en": "Creative Center"},
        "4": {"zh": "设计学院", "en": "Design Academy"},
        "5": {"zh": "品牌实验室", "en": "Brand Lab"},
        "6": {"zh": "视觉研究院", "en": "Visual Research Institute"},
        "7": {"zh": "创意园区", "en": "Creative Park"},
        "8": {"zh": "设计之城", "en": "City of Design"},
        "9": {"zh": "艺术圣殿", "en": "Art Sanctuary"},
        "10": {"zh": "创造神殿", "en": "Temple of Creation"},
    },
    "MEDIA": {
        "1": {"zh": "报刊室", "en": "Newsroom"},
        "2": {"zh": "编辑部", "en": "Editorial Office"},
        "3": {"zh": "媒体中心", "en": "Media Center"},
        "4": {"zh": "内容工厂", "en": "Content Factory"},
        "5": {"zh": "自媒体矩阵", "en": "Self-Media Matrix"},
        "6": {"zh": "传媒集团", "en": "Media Group"},
        "7": {"zh": "全球媒体网络", "en": "Global Media Network"},
        "8": {"zh": "内容帝国", "en": "Content Empire"},
        "9": {"zh": "传播圣殿", "en": "Communication Sanctuary"},
        "10": {"zh": "文明广播塔", "en": "Civilization Broadcast Tower"},
    },
    "SCIENCE": {
        "1": {"zh": "实验桌", "en": "Experiment Desk"},
        "2": {"zh": "实验室", "en": "Laboratory"},
        "3": {"zh": "研究所", "en": "Research Institute"},
        "4": {"zh": "科学院", "en": "Academy of Sciences"},
        "5": {"zh": "国家实验中心", "en": "National Experiment Center"},
        "6": {"zh": "粒子实验基地", "en": "Particle Experiment Base"},
        "7": {"zh": "未来研究院", "en": "Future Research Institute"},
        "8": {"zh": "科技联盟", "en": "Science & Tech Alliance"},
        "9": {"zh": "科学圣殿", "en": "Science Sanctuary"},
        "10": {"zh": "真理之塔", "en": "Tower of Truth"},
    },
    "LANGUAGE": {
        "1": {"zh": "书屋", "en": "Book House"},
        "2": {"zh": "翻译社", "en": "Translation Agency"},
        "3": {"zh": "语言学院", "en": "Language Academy"},
        "4": {"zh": "国际交流中心", "en": "International Exchange Center"},
        "5": {"zh": "文化研究院", "en": "Cultural Research Institute"},
        "6": {"zh": "文明交流塔", "en": "Civilization Exchange Tower"},
        "7": {"zh": "全球语言中心", "en": "Global Language Center"},
        "8": {"zh": "文化联盟", "en": "Cultural Alliance"},
        "9": {"zh": "世界语言殿堂", "en": "World Language Hall"},
        "10": {"zh": "文明传播核心", "en": "Civilization Communication Core"},
    },
    "HEALTH": {
        "1": {"zh": "训练场", "en": "Training Ground"},
        "2": {"zh": "健身馆", "en": "Fitness Center"},
        "3": {"zh": "医疗站", "en": "Medical Station"},
        "4": {"zh": "康复中心", "en": "Rehabilitation Center"},
        "5": {"zh": "生命科学院", "en": "Life Science Academy"},
        "6": {"zh": "健康研究院", "en": "Health Research Institute"},
        "7": {"zh": "生命管理中心", "en": "Life Management Center"},
        "8": {"zh": "健康圣殿", "en": "Health Sanctuary"},
        "9": {"zh": "健康都市", "en": "Health Metropolis"},
        "10": {"zh": "永续生命中心", "en": "Eternal Life Center"},
    },
    "FINANCE": {
        "1": {"zh": "钱庄", "en": "Money House"},
        "2": {"zh": "银行", "en": "Bank"},
        "3": {"zh": "证券中心", "en": "Securities Center"},
        "4": {"zh": "投资机构", "en": "Investment Institution"},
        "5": {"zh": "金融大厦", "en": "Financial Tower"},
        "6": {"zh": "资本市场", "en": "Capital Market"},
        "7": {"zh": "国际基金会", "en": "International Foundation"},
        "8": {"zh": "全球金融城", "en": "Global Financial City"},
        "9": {"zh": "数字银行联盟", "en": "Digital Banking Alliance"},
        "10": {"zh": "财富核心", "en": "Wealth Core"},
    },
    "DIGITAL": {
        "1": {"zh": "服务器机房", "en": "Server Room"},
        "2": {"zh": "数据中心", "en": "Data Center"},
        "3": {"zh": "云平台", "en": "Cloud Platform"},
        "4": {"zh": "数字园区", "en": "Digital Park"},
        "5": {"zh": "数字城市", "en": "Digital City"},
        "6": {"zh": "智能城市", "en": "Smart City"},
        "7": {"zh": "数字联邦", "en": "Digital Federation"},
        "8": {"zh": "虚拟文明中心", "en": "Virtual Civilization Center"},
        "9": {"zh": "元宇宙核心", "en": "Metaverse Core"},
        "10": {"zh": "数字文明主脑", "en": "Digital Civilization Mainframe"},
    },
    "SOCIETY": {
        "1": {"zh": "议事厅", "en": "Council Hall"},
        "2": {"zh": "公会", "en": "Guild"},
        "3": {"zh": "市政厅", "en": "City Hall"},
        "4": {"zh": "管理中心", "en": "Management Center"},
        "5": {"zh": "社会服务中心", "en": "Social Service Center"},
        "6": {"zh": "组织联盟", "en": "Organization Alliance"},
        "7": {"zh": "区域治理中心", "en": "Regional Governance Center"},
        "8": {"zh": "文明议会", "en": "Civilization Parliament"},
        "9": {"zh": "世界联盟", "en": "World Alliance"},
        "10": {"zh": "文明管理核心", "en": "Civilization Governance Core"},
    },
}

# Building templates — one per skill, assigned to civilization type
# (skill_name, building_name, building_name_en, icon, civ_type, era, gx, gy, desc_zh, desc_en)
BUILDING_SEEDS_FULL: list[dict] = [
    # ── 知识文明 / KNOWLEDGE ────────────────────────
    {
        "skill_name": "Reading",
        "name": "阅读之塔",
        "name_en": "Reading Tower",
        "description": "深度阅读的力量——从文字中提取智慧，构建理解世界的框架。",
        "description_en": "The power of deep reading — extract wisdom from text and build frameworks for understanding the world.",
        "icon": "📖",
        "region": "知识区",
        "region_en": "Knowledge Region",
        "civilization_type": "KNOWLEDGE",
        "era": "WILDERNESS",
        "position_x": 0, "position_y": 0,
    },
    {
        "skill_name": "Research",
        "name": "研究殿堂",
        "name_en": "Research Hall",
        "description": "系统性探索未知——从文献调研到实验验证，推动知识边界。",
        "description_en": "Systematic exploration of the unknown — from literature review to experimental validation, pushing knowledge boundaries.",
        "icon": "🔬",
        "region": "知识区",
        "region_en": "Knowledge Region",
        "civilization_type": "KNOWLEDGE",
        "era": "WILDERNESS",
        "position_x": 0, "position_y": 1,
    },
    {
        "skill_name": "Learning",
        "name": "学习圣殿",
        "name_en": "Learning Sanctuary",
        "description": "学会如何学习——掌握元认知策略，让每一次学习都更高效。",
        "description_en": "Learn how to learn — master meta-cognitive strategies to make every learning session more effective.",
        "icon": "🧠",
        "region": "知识区",
        "region_en": "Knowledge Region",
        "civilization_type": "KNOWLEDGE",
        "era": "WILDERNESS",
        "position_x": 0, "position_y": 2,
    },
    {
        "skill_name": "Memory",
        "name": "记忆宫殿",
        "name_en": "Memory Palace",
        "description": "构建第二大脑——用系统化方法管理知识，让记忆成为创造力的源泉。",
        "description_en": "Build a second brain — systematize knowledge management so memory becomes the source of creativity.",
        "icon": "🏰",
        "region": "知识区",
        "region_en": "Knowledge Region",
        "civilization_type": "KNOWLEDGE",
        "era": "WILDERNESS",
        "position_x": 0, "position_y": 3,
    },
    {
        "skill_name": "Info Retrieval",
        "name": "信息灯塔",
        "name_en": "Info Lighthouse",
        "description": "在信息海洋中精准导航——快速定位、筛选和整合关键信息。",
        "description_en": "Navigate the information ocean with precision — quickly locate, filter, and integrate key information.",
        "icon": "🔍",
        "region": "知识区",
        "region_en": "Knowledge Region",
        "civilization_type": "KNOWLEDGE",
        "era": "AGRICULTURE",
        "position_x": 0, "position_y": 4,
    },
    # ── AI文明 / AI ──────────────────────────────────
    {
        "skill_name": "Prompt Engineering",
        "name": "语言学院",
        "name_en": "Language Academy",
        "description": "掌握提示词设计艺术，驱动大语言模型完成复杂任务。",
        "description_en": "Master the art of prompt design to drive LLMs for complex tasks.",
        "icon": "📝",
        "region": "AI区",
        "region_en": "AI Region",
        "civilization_type": "AI",
        "era": "AI",
        "position_x": 1, "position_y": 0,
    },
    {
        "skill_name": "RAG",
        "name": "知识殿堂",
        "name_en": "Knowledge Hall",
        "description": "构建检索增强生成系统，融合向量搜索与知识图谱。",
        "description_en": "Build RAG systems combining vector search and knowledge graphs.",
        "icon": "📚",
        "region": "AI区",
        "region_en": "AI Region",
        "civilization_type": "AI",
        "era": "AI",
        "position_x": 1, "position_y": 1,
    },
    {
        "skill_name": "Agent",
        "name": "智能体中心",
        "name_en": "Agent Center",
        "description": "构建自主智能体系统，实现工具调用、任务规划与自主决策。",
        "description_en": "Build autonomous agent systems with tool calling, task planning, and independent decision-making.",
        "icon": "🤖",
        "region": "AI区",
        "region_en": "AI Region",
        "civilization_type": "AI",
        "era": "AI",
        "position_x": 1, "position_y": 2,
    },
    {
        "skill_name": "LangGraph",
        "name": "智能体工坊",
        "name_en": "Agent Workshop",
        "description": "构建状态驱动的多Agent协作系统，实现复杂智能体编排。",
        "description_en": "Build state-driven multi-agent collaboration systems for complex agent orchestration.",
        "icon": "🔗",
        "region": "AI区",
        "region_en": "AI Region",
        "civilization_type": "AI",
        "era": "AI",
        "position_x": 1, "position_y": 3,
    },
    {
        "skill_name": "Workflow Design",
        "name": "自动化工坊",
        "name_en": "Automation Workshop",
        "description": "设计多步骤任务执行工作流，实现复杂流程自动化与Agent编排。",
        "description_en": "Design multi-step task execution workflows for complex automation and agent orchestration.",
        "icon": "⚙️",
        "region": "AI区",
        "region_en": "AI Region",
        "civilization_type": "AI",
        "era": "INFORMATION",
        "position_x": 2, "position_y": 0,
    },
    # ── 工程文明 / ENGINEERING ────────────────────────
    {
        "skill_name": "Python",
        "name": "Python工坊",
        "name_en": "Python Workshop",
        "description": "掌握Python编程——从基础语法到异步编程与生态库。",
        "description_en": "Master Python programming — from fundamentals to async, typing, and ecosystem libraries.",
        "icon": "🐍",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INDUSTRY",
        "position_x": 3, "position_y": 0,
    },
    {
        "skill_name": "Frontend",
        "name": "前端工坊",
        "name_en": "Frontend Workshop",
        "description": "构建现代前端应用——React、TypeScript、Tailwind技术栈。",
        "description_en": "Build modern frontend applications with React, TypeScript, and Tailwind CSS.",
        "icon": "🎨",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INDUSTRY",
        "position_x": 3, "position_y": 1,
    },
    {
        "skill_name": "Backend",
        "name": "后端工坊",
        "name_en": "Backend Workshop",
        "description": "构建可扩展的后端系统——API设计、数据库和系统架构。",
        "description_en": "Build scalable backend systems with API design, databases, and system architecture.",
        "icon": "🖥️",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INDUSTRY",
        "position_x": 3, "position_y": 2,
    },
    {
        "skill_name": "Architecture",
        "name": "架构圣殿",
        "name_en": "Architecture Temple",
        "description": "系统架构设计——微服务、分布式系统和云原生架构。",
        "description_en": "System architecture design covering microservices, distributed systems, and cloud-native architecture.",
        "icon": "🏗️",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INFORMATION",
        "position_x": 4, "position_y": 0,
    },
    {
        "skill_name": "Automation",
        "name": "自动化中心",
        "name_en": "Automation Center",
        "description": "自动化工作流设计——CI/CD、脚本化和流程编排。",
        "description_en": "Automation workflow design including CI/CD, scripting, and process orchestration.",
        "icon": "🔄",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INFORMATION",
        "position_x": 4, "position_y": 1,
    },
    {
        "skill_name": "JavaScript",
        "name": "JavaScript工坊",
        "name_en": "JavaScript Workshop",
        "description": "现代JavaScript开发——ES6+、异步模式和模块系统。",
        "description_en": "Build modern JavaScript applications with ES6+, async patterns, and module systems.",
        "icon": "💛",
        "region": "工程区",
        "region_en": "Engineering Region",
        "civilization_type": "ENGINEERING",
        "era": "INDUSTRY",
        "position_x": 3, "position_y": 3,
    },
    # ── 商业文明 / BUSINESS ───────────────────────────
    {
        "skill_name": "Marketing",
        "name": "市场中心",
        "name_en": "Marketing Center",
        "description": "市场营销策略——数字营销、品牌建设和增长黑客。",
        "description_en": "Marketing strategy covering digital marketing, brand building, and growth hacking.",
        "icon": "📢",
        "region": "商业区",
        "region_en": "Business Region",
        "civilization_type": "BUSINESS",
        "era": "INTELLIGENCE",
        "position_x": 5, "position_y": 0,
    },
    {
        "skill_name": "Product Strategy",
        "name": "产品中心",
        "name_en": "Product Center",
        "description": "产品战略与路线图——优先级框架和产品市场契合分析。",
        "description_en": "Product strategy and roadmap — prioritization frameworks and product-market fit analysis.",
        "icon": "🎯",
        "region": "商业区",
        "region_en": "Business Region",
        "civilization_type": "BUSINESS",
        "era": "INTELLIGENCE",
        "position_x": 5, "position_y": 1,
    },
    {
        "skill_name": "Business",
        "name": "商业中心",
        "name_en": "Business Center",
        "description": "商业思维与模式设计——理解价值创造、捕获和交付的核心逻辑。",
        "description_en": "Business thinking and model design — understanding core logic of value creation, capture, and delivery.",
        "icon": "💼",
        "region": "商业区",
        "region_en": "Business Region",
        "civilization_type": "BUSINESS",
        "era": "INTELLIGENCE",
        "position_x": 5, "position_y": 2,
    },
    {
        "skill_name": "Sales",
        "name": "销售中心",
        "name_en": "Sales Center",
        "description": "销售能力与客户关系——解决方案销售和谈判技巧。",
        "description_en": "Sales skills and customer relationships — solution selling and negotiation techniques.",
        "icon": "🤝",
        "region": "商业区",
        "region_en": "Business Region",
        "civilization_type": "BUSINESS",
        "era": "INTELLIGENCE",
        "position_x": 5, "position_y": 3,
    },
    # ── 设计文明 / DESIGN ─────────────────────────────
    {
        "skill_name": "UI Design",
        "name": "UI设计院",
        "name_en": "UI Design Institute",
        "description": "创建直观、无障碍、视觉精美的用户界面与设计系统。",
        "description_en": "Create intuitive, accessible, and visually polished user interfaces with design systems.",
        "icon": "🖌️",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -1, "position_y": 0,
    },
    {
        "skill_name": "UX Design",
        "name": "UX研究院",
        "name_en": "UX Research Institute",
        "description": "用户体验设计——用户研究、信息架构和交互设计。",
        "description_en": "User experience design — user research, information architecture, and interaction design.",
        "icon": "👥",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -1, "position_y": 1,
    },
    {
        "skill_name": "Branding",
        "name": "品牌实验室",
        "name_en": "Brand Lab",
        "description": "品牌战略与视觉识别——构建有影响力的品牌体系。",
        "description_en": "Brand strategy and visual identity design to build influential brand systems.",
        "icon": "✨",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -1, "position_y": 2,
    },
    {
        "skill_name": "Design",
        "name": "设计学院",
        "name_en": "Design Academy",
        "description": "通用设计思维与方法论——设计原则、色彩理论和排版。",
        "description_en": "General design thinking and methodology — design principles, color theory, and typography.",
        "icon": "🎭",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -1, "position_y": 3,
    },
    {
        "skill_name": "Creativity",
        "name": "创意中心",
        "name_en": "Creativity Center",
        "description": "创造性思维与创新方法论——设计思维和头脑风暴技巧。",
        "description_en": "Creative thinking and innovation methodology — design thinking and brainstorming techniques.",
        "icon": "💡",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -1, "position_y": 4,
    },
    {
        "skill_name": "User Research",
        "name": "用户研究院",
        "name_en": "User Research Institute",
        "description": "用户研究与需求分析——通过访谈、测试和数据为产品决策提供依据。",
        "description_en": "User research and needs analysis to inform product decisions through interviews, testing, and data.",
        "icon": "🔎",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -2, "position_y": 2,
    },
    {
        "skill_name": "Design Systems",
        "name": "设计系统工坊",
        "name_en": "Design Systems Workshop",
        "description": "构建可扩展的设计系统——设计Token、组件库和文档。",
        "description_en": "Build scalable design systems with tokens, components, patterns, and documentation.",
        "icon": "🧩",
        "region": "设计区",
        "region_en": "Design Region",
        "civilization_type": "DESIGN",
        "era": "INTELLIGENCE",
        "position_x": -2, "position_y": 3,
    },
    # ── 媒体文明 / MEDIA ──────────────────────────────
    {
        "skill_name": "Writing",
        "name": "写作中心",
        "name_en": "Writing Center",
        "description": "写作与内容创作——技术写作、创意写作和商业写作。",
        "description_en": "Writing and content creation — technical, creative, and business writing.",
        "icon": "✍️",
        "region": "媒体区",
        "region_en": "Media Region",
        "civilization_type": "MEDIA",
        "era": "INTELLIGENCE",
        "position_x": -3, "position_y": 0,
    },
    {
        "skill_name": "Video",
        "name": "视频中心",
        "name_en": "Video Center",
        "description": "视频制作与编辑——脚本撰写、拍摄和后期制作。",
        "description_en": "Video production and editing — scripting, filming, and post-production.",
        "icon": "🎬",
        "region": "媒体区",
        "region_en": "Media Region",
        "civilization_type": "MEDIA",
        "era": "INTELLIGENCE",
        "position_x": -3, "position_y": 1,
    },
    {
        "skill_name": "Editing",
        "name": "编辑中心",
        "name_en": "Editing Center",
        "description": "内容编辑与审校——确保内容质量和一致性。",
        "description_en": "Content editing and proofreading to ensure quality and consistency.",
        "icon": "📋",
        "region": "媒体区",
        "region_en": "Media Region",
        "civilization_type": "MEDIA",
        "era": "INTELLIGENCE",
        "position_x": -3, "position_y": 2,
    },
    {
        "skill_name": "Technical Writing",
        "name": "技术写作中心",
        "name_en": "Tech Writing Center",
        "description": "技术文档写作——清晰的API文档、工程指南和技术博客。",
        "description_en": "Technical documentation — clear API references, engineering guides, and tech blogs.",
        "icon": "📐",
        "region": "媒体区",
        "region_en": "Media Region",
        "civilization_type": "MEDIA",
        "era": "INTELLIGENCE",
        "position_x": -3, "position_y": 3,
    },
    # ── 科学文明 / SCIENCE ────────────────────────────
    {
        "skill_name": "Mathematics",
        "name": "数学圣殿",
        "name_en": "Mathematics Sanctuary",
        "description": "数学基础——线性代数、概率论和优化理论。",
        "description_en": "Foundational mathematics — linear algebra, probability theory, and optimization.",
        "icon": "📐",
        "region": "科学区",
        "region_en": "Science Region",
        "civilization_type": "SCIENCE",
        "era": "ACADEMY",
        "position_x": -2, "position_y": -1,
    },
    {
        "skill_name": "Statistics",
        "name": "统计中心",
        "name_en": "Statistics Center",
        "description": "统计分析与数据推理——假设检验、回归分析和贝叶斯方法。",
        "description_en": "Statistical analysis and data inference — hypothesis testing, regression, and Bayesian methods.",
        "icon": "📊",
        "region": "科学区",
        "region_en": "Science Region",
        "civilization_type": "SCIENCE",
        "era": "ACADEMY",
        "position_x": -2, "position_y": 0,
    },
    {
        "skill_name": "Physics",
        "name": "物理研究院",
        "name_en": "Physics Institute",
        "description": "物理学基础与工程物理——力学、电磁学和量子力学核心概念。",
        "description_en": "Foundations of physics — core concepts of mechanics, electromagnetism, and quantum mechanics.",
        "icon": "⚛️",
        "region": "科学区",
        "region_en": "Science Region",
        "civilization_type": "SCIENCE",
        "era": "ACADEMY",
        "position_x": -2, "position_y": 1,
    },
    {
        "skill_name": "Research Methodology",
        "name": "方法论中心",
        "name_en": "Methodology Center",
        "description": "科学研究方法论——实验设计、数据收集和学术写作。",
        "description_en": "Scientific research methodology — experiment design, data collection, and academic writing.",
        "icon": "📋",
        "region": "科学区",
        "region_en": "Science Region",
        "civilization_type": "SCIENCE",
        "era": "ACADEMY",
        "position_x": -2, "position_y": 2,
    },
    # ── 语言文明 / LANGUAGE ──────────────────────────
    {
        "skill_name": "English",
        "name": "英语学院",
        "name_en": "English Academy",
        "description": "英语综合能力——听说读写和专业英语应用。",
        "description_en": "Comprehensive English ability — listening, speaking, reading, writing, and professional English.",
        "icon": "🇬🇧",
        "region": "语言区",
        "region_en": "Language Region",
        "civilization_type": "LANGUAGE",
        "era": "AGRICULTURE",
        "position_x": -1, "position_y": -1,
    },
    {
        "skill_name": "Translation",
        "name": "翻译中心",
        "name_en": "Translation Center",
        "description": "翻译与跨语言沟通——专业翻译和本地化。",
        "description_en": "Translation and cross-language communication — professional translation and localization.",
        "icon": "🌐",
        "region": "语言区",
        "region_en": "Language Region",
        "civilization_type": "LANGUAGE",
        "era": "AGRICULTURE",
        "position_x": -1, "position_y": -2,
    },
    {
        "skill_name": "Communication",
        "name": "沟通中心",
        "name_en": "Communication Center",
        "description": "沟通与表达——演讲、谈判和跨文化沟通。",
        "description_en": "Communication and expression — public speaking, negotiation, and cross-cultural communication.",
        "icon": "🗣️",
        "region": "语言区",
        "region_en": "Language Region",
        "civilization_type": "LANGUAGE",
        "era": "AGRICULTURE",
        "position_x": -1, "position_y": -3,
    },
    {
        "skill_name": "Public Speaking",
        "name": "演讲厅",
        "name_en": "Public Speaking Hall",
        "description": "公众演讲与表达艺术——叙事结构、舞台表现和受众互动。",
        "description_en": "Public speaking and presentation arts — narrative structure, stage presence, and audience engagement.",
        "icon": "🎤",
        "region": "语言区",
        "region_en": "Language Region",
        "civilization_type": "LANGUAGE",
        "era": "AGRICULTURE",
        "position_x": 0, "position_y": -1,
    },
    # ── 健康文明 / HEALTH ─────────────────────────────
    {
        "skill_name": "Health",
        "name": "健康中心",
        "name_en": "Health Center",
        "description": "健康管理与生活方式优化——营养学、睡眠科学和压力管理。",
        "description_en": "Health management and lifestyle optimization — nutrition, sleep science, and stress management.",
        "icon": "💚",
        "region": "健康区",
        "region_en": "Health Region",
        "civilization_type": "HEALTH",
        "era": "DIGITAL",
        "position_x": 4, "position_y": -1,
    },
    {
        "skill_name": "Exercise",
        "name": "训练中心",
        "name_en": "Exercise Center",
        "description": "运动科学与体能训练——制定科学的运动和恢复计划。",
        "description_en": "Exercise science and physical training — develop scientific exercise and recovery plans.",
        "icon": "🏃",
        "region": "健康区",
        "region_en": "Health Region",
        "civilization_type": "HEALTH",
        "era": "DIGITAL",
        "position_x": 4, "position_y": -2,
    },
    {
        "skill_name": "Nutrition",
        "name": "营养中心",
        "name_en": "Nutrition Center",
        "description": "营养学知识与饮食规划——理解宏量和微量营养素的核心作用。",
        "description_en": "Nutrition knowledge and diet planning — understanding core roles of macro and micronutrients.",
        "icon": "🥗",
        "region": "健康区",
        "region_en": "Health Region",
        "civilization_type": "HEALTH",
        "era": "DIGITAL",
        "position_x": 4, "position_y": -3,
    },
    # ── 金融文明 / FINANCE ────────────────────────────
    {
        "skill_name": "Finance",
        "name": "金融中心",
        "name_en": "Finance Center",
        "description": "金融学基础与投资理论——资产定价、风险管理和投资组合。",
        "description_en": "Finance fundamentals and investment theory — asset pricing, risk management, and portfolio construction.",
        "icon": "💰",
        "region": "金融区",
        "region_en": "Finance Region",
        "civilization_type": "FINANCE",
        "era": "INFORMATION",
        "position_x": 5, "position_y": -1,
    },
    {
        "skill_name": "Economics",
        "name": "经济研究院",
        "name_en": "Economics Institute",
        "description": "经济学思维与分析——宏观经济和微观经济核心原理。",
        "description_en": "Economic thinking and analysis — core principles of macro and micro economics.",
        "icon": "📈",
        "region": "金融区",
        "region_en": "Finance Region",
        "civilization_type": "FINANCE",
        "era": "INFORMATION",
        "position_x": 5, "position_y": -2,
    },
    {
        "skill_name": "Investment",
        "name": "投资中心",
        "name_en": "Investment Center",
        "description": "投资分析与决策——价值投资、量化分析和风险对冲策略。",
        "description_en": "Investment analysis and decision-making — value investing, quantitative analysis, and risk hedging.",
        "icon": "🏦",
        "region": "金融区",
        "region_en": "Finance Region",
        "civilization_type": "FINANCE",
        "era": "DIGITAL",
        "position_x": 6, "position_y": -1,
    },
    {
        "skill_name": "Risk Analysis",
        "name": "风控中心",
        "name_en": "Risk Analysis Center",
        "description": "风险分析与决策科学——金融风险、项目风险和安全风险评估。",
        "description_en": "Risk analysis and decision science — financial risk, project risk, and security risk assessment.",
        "icon": "🛡️",
        "region": "金融区",
        "region_en": "Finance Region",
        "civilization_type": "FINANCE",
        "era": "DIGITAL",
        "position_x": 6, "position_y": -2,
    },
    # ── 数字文明 / DIGITAL ────────────────────────────
    {
        "skill_name": "Coding",
        "name": "编码中心",
        "name_en": "Coding Center",
        "description": "编程与软件开发——算法、数据结构和软件工程实践。",
        "description_en": "Programming and software development — algorithms, data structures, and engineering practices.",
        "icon": "💻",
        "region": "数字区",
        "region_en": "Digital Region",
        "civilization_type": "DIGITAL",
        "era": "INFORMATION",
        "position_x": 2, "position_y": -1,
    },
    {
        "skill_name": "Database",
        "name": "数据库中心",
        "name_en": "Database Center",
        "description": "数据库设计与优化——SQL、NoSQL和数据建模。",
        "description_en": "Database design and optimization — SQL, NoSQL, and data modeling.",
        "icon": "🗄️",
        "region": "数字区",
        "region_en": "Digital Region",
        "civilization_type": "DIGITAL",
        "era": "INFORMATION",
        "position_x": 2, "position_y": -2,
    },
    {
        "skill_name": "Cloud",
        "name": "云端中心",
        "name_en": "Cloud Center",
        "description": "云计算与DevOps——容器化、Kubernetes和云服务架构。",
        "description_en": "Cloud computing and DevOps — containerization, Kubernetes, and cloud service architecture.",
        "icon": "☁️",
        "region": "数字区",
        "region_en": "Digital Region",
        "civilization_type": "DIGITAL",
        "era": "INFORMATION",
        "position_x": 2, "position_y": -3,
    },
    {
        "skill_name": "System Design",
        "name": "系统设计中心",
        "name_en": "System Design Center",
        "description": "可扩展分布式系统设计——负载均衡、缓存和数据库分片。",
        "description_en": "Scalable distributed systems — load balancing, caching, and database sharding.",
        "icon": "🏛️",
        "region": "数字区",
        "region_en": "Digital Region",
        "civilization_type": "DIGITAL",
        "era": "INFORMATION",
        "position_x": 3, "position_y": -1,
    },
    {
        "skill_name": "Algorithms",
        "name": "算法研究院",
        "name_en": "Algorithms Institute",
        "description": "算法分析与实现——数据结构和复杂度分析。",
        "description_en": "Algorithm analysis and implementation — data structures and complexity analysis.",
        "icon": "🔢",
        "region": "数字区",
        "region_en": "Digital Region",
        "civilization_type": "DIGITAL",
        "era": "ACADEMY",
        "position_x": 1, "position_y": -1,
    },
    # ── 社会文明 / SOCIETY ────────────────────────────
    {
        "skill_name": "Leadership",
        "name": "领导力中心",
        "name_en": "Leadership Center",
        "description": "领导力与团队管理——辅导、授权、冲突解决和战略沟通。",
        "description_en": "Leadership and team management — mentoring, delegation, conflict resolution, and strategic communication.",
        "icon": "👑",
        "region": "社会区",
        "region_en": "Society Region",
        "civilization_type": "SOCIETY",
        "era": "DIGITAL",
        "position_x": -3, "position_y": -1,
    },
    {
        "skill_name": "Management",
        "name": "管理中心",
        "name_en": "Management Center",
        "description": "项目管理与组织协调——敏捷、Scrum和OKR方法论。",
        "description_en": "Project management and organizational coordination — Agile, Scrum, and OKR methodologies.",
        "icon": "📋",
        "region": "社会区",
        "region_en": "Society Region",
        "civilization_type": "SOCIETY",
        "era": "DIGITAL",
        "position_x": -3, "position_y": -2,
    },
    {
        "skill_name": "Organization",
        "name": "组织中心",
        "name_en": "Organization Center",
        "description": "组织设计与制度建设——构建高效协作的团队和组织结构。",
        "description_en": "Organizational design and institution building — efficient collaborative team structures.",
        "icon": "🏢",
        "region": "社会区",
        "region_en": "Society Region",
        "civilization_type": "SOCIETY",
        "era": "DIGITAL",
        "position_x": -3, "position_y": -3,
    },
    {
        "skill_name": "Career Planning",
        "name": "职业发展中心",
        "name_en": "Career Center",
        "description": "职业规划与发展策略——技能映射、机会评估和个人品牌建设。",
        "description_en": "Career planning and development — skill mapping, opportunity assessment, and personal brand building.",
        "icon": "🚀",
        "region": "社会区",
        "region_en": "Society Region",
        "civilization_type": "SOCIETY",
        "era": "DIGITAL",
        "position_x": -2, "position_y": -3,
    },
    # ── Cross-domain: Data Analysis ────────────────────
    {
        "skill_name": "Data Analysis",
        "name": "数据分析中心",
        "name_en": "Data Analysis Center",
        "description": "数据分析与洞察挖掘——统计分析、可视化和探索性分析。",
        "description_en": "Data analysis and insight extraction — statistical analysis, visualization, and exploratory analysis.",
        "icon": "📊",
        "region": "科学区",
        "region_en": "Science Region",
        "civilization_type": "SCIENCE",
        "era": "INFORMATION",
        "position_x": -2, "position_y": 3,
    },
]


def seed_buildings_full(db: Session) -> int:
    """Insert building templates for all skills. Idempotent.

    Returns:
        Number of templates inserted.
    """
    inserted = 0

    for data in BUILDING_SEEDS_FULL:
        skill_name = data.pop("skill_name")
        civ_type = data.pop("civilization_type")

        # Look up skill by name
        skill = db.query(Skill).filter(Skill.name == skill_name).first()
        if skill is None:
            print(f"  ⚠️  Skill '{skill_name}' not found — skipping building template")
            continue

        # Check if template already exists for this skill
        existing = db.query(BuildingTemplate).filter(
            BuildingTemplate.skill_id == skill.id
        ).first()
        if existing:
            # Update civ type and era if they were NULL
            if existing.civilization_type is None:
                existing.civilization_type = civ_type
            if existing.era is None:
                existing.era = data.get("era")
            continue

        # Use civ type level names (all buildings in same civ share the growth ladder)
        level_names = CIV_LEVEL_NAMES.get(civ_type, {})

        template = BuildingTemplate(
            skill_id=skill.id,
            level_names=level_names,
            civilization_type=civ_type,
            max_level=10,
            **data,
        )
        db.add(template)
        inserted += 1

    if inserted:
        db.commit()
        print(f"  🏗️  Seeded {inserted} building templates (full catalog, 10-level)")

    return inserted
